name: Post CHANGELOG to Slack

on:
  push:
    branches:
      - main

jobs:
  post_changelog_to_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Read the latest CHANGELOG entry
        id: changelog
        run: |
          # Read the CHANGELOG.md file and extract the latest entry
          CHANGELOG=$(awk '/^##/{if (p) exit; p=1} p' CHANGELOG.md)
          echo "$CHANGELOG"
          echo "::set-output name=changelog::$CHANGELOG"

      - name: Post to Slack
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: |
          curl -X POST https://slack.com/api/chat.postMessage \
          -H "Authorization: Bearer $SLACK_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{
            "channel": "CHANNEL_ID",
            "text": "'"${{ steps.changelog.outputs.changelog }}"'",
            "thread_ts": "MESSAGE_TS"
          }'
