name: Post CHANGELOG to Slack

on:
  push:
    branches:
      - main

jobs:
  post_changelog_to_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Read the latest CHANGELOG entry
        id: changelog
        run: |
          # Extract the content under the most recent version header in CHANGELOG.md
          CHANGELOG=$(awk '/^##/{if (p) exit; p=1} p' CHANGELOG.md)
          
          # Debugging: Print the extracted changelog content
          echo "$CHANGELOG"
          
          # Write the extracted changelog to the environment file
          echo "CHANGELOG_CONTENT<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send to Slack via Webhook
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          CHANGELOG_CONTENT: ${{ env.CHANGELOG_CONTENT }}
        run: |
          # Format the changelog content for Slack
          FORMATTED_CHANGELOG=$(echo "${CHANGELOG_CONTENT}" | sed 's/"/\\"/g')
          
          # Send the changelog content to Slack in markdown format
          curl -X POST $SLACK_WEBHOOK_URL \
          -H 'Content-type: application/json' \
          --data '{
            "text": "Here is the latest changelog:",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "'"${FORMATTED_CHANGELOG}"'"
                }
              }
            ]
          }'
