name: Post CHANGELOG to Slack

on:
  push:
    branches:
      - main

jobs:
  post_changelog_to_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Read the latest CHANGELOG entry
        id: changelog
        run: |
          # Extract the content under the most recent version header in CHANGELOG.md
          CHANGELOG=$(awk '/^## \[.*\]/ {if (p) exit; p=1} p' CHANGELOG.md)
          
          # Debugging: Print the extracted changelog content
          echo "Original CHANGELOG:"
          echo "$CHANGELOG"
          
          CHANGELOG=$(echo "$CHANGELOG" | sed -E 's/^### (.+)/*\1*/')
          
          # Replace "**" with "*" for bold to italic conversion in Slack
          CHANGELOG=$(echo "$CHANGELOG" | sed 's/\*\*/\*/g')

          # Debugging: Print the changelog after bold to italic conversion
          echo "After Bold to Italic Conversion:"
          echo "$CHANGELOG"

          # Replace markdown URLs with Slack format URLs
          CHANGELOG=$(echo "$CHANGELOG" | sed -E 's/\\?([[][^]]+]\\?)\\?[(]([^()]+)\\?[)]/<\2|\1>/g')

          # Debugging: Print the changelog after URL conversion
          echo "After URL Conversion:"
          echo "$CHANGELOG"

          # Write the modified changelog to the environment file
          echo "CHANGELOG_CONTENT<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send to Slack via Webhook
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          CHANGELOG_CONTENT: ${{ env.CHANGELOG_CONTENT }}
        run: |
          # Escape double quotes in the changelog content to avoid JSON syntax errors
          ESCAPED_CHANGELOG_CONTENT=$(echo "$CHANGELOG_CONTENT" | sed 's/"/\\"/g')

          # Debugging: Print the escaped changelog content
          echo "Escaped CHANGELOG_CONTENT:"
          echo "$ESCAPED_CHANGELOG_CONTENT"

          # Send the changelog content to Slack in markdown format
          curl -X POST $SLACK_WEBHOOK_URL \
          -H 'Content-type: application/json' \
          --data '{
            "text": "Here is the latest changelog:",
            "attachments": [
              {
                "color": "#36a64f",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "'"${ESCAPED_CHANGELOG_CONTENT}"'"
                    }
                  }
                ]
              }
            ]
          }'
