name: Post CHANGELOG to Slack

on:
  push:
    branches:
      - main

jobs:
  post_changelog_to_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Read the latest CHANGELOG entry
        id: changelog
        run: |
          # Extract the section for the latest version (0.9.0 in this example)
          CHANGELOG=$(awk '/^## \[0\.9\.0\]/{flag=1;next}/^## \[/{flag=0}flag' CHANGELOG.md)
          echo "$CHANGELOG"  # Debugging: print the extracted changelog content
          echo "::set-output name=changelog::$CHANGELOG"

      - name: Send to Slack via Webhook
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          CHANGELOG_CONTENT: ${{ steps.changelog.outputs.changelog }}
        run: |
          echo "Sending the following content to Slack:"  # Debugging: print content before sending
          echo "$CHANGELOG_CONTENT"
          curl -X POST $SLACK_WEBHOOK_URL \
          -H 'Content-type: application/json' \
          --data '{"text": "'"$CHANGELOG_CONTENT"'"}'
