name: Post CHANGELOG to Slack

on:
  push:
    branches:
      - main

jobs:
  post_changelog_to_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Read the latest CHANGELOG entry
        id: changelog
        run: |
          # Extract the content under the most recent version header in CHANGELOG.md
          # This regex matches the latest version section and captures everything until the next version or end of file
          LATEST_VERSION=$(awk '/^##/{if (p) exit; p=1} p' CHANGELOG.md)
          
          # Ensure proper formatting by replacing newlines with spaces and escaping double quotes
          FORMATTED_CHANGELOG=$(echo "$LATEST_VERSION" | sed ':a;N;$!ba;s/\n/\\n/g' | sed 's/"/\\"/g')

          # Output the formatted changelog content to the environment file
          echo "CHANGELOG_CONTENT<<EOF" >> $GITHUB_ENV
          echo "$FORMATTED_CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send to Slack via Webhook
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          CHANGELOG_CONTENT: ${{ env.CHANGELOG_CONTENT }}
        run: |
          # Send the changelog content to Slack in markdown format
          curl -X POST $SLACK_WEBHOOK_URL \
          -H 'Content-type: application/json' \
          --data '{
            "text": "Here is the latest changelog:",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ```'"$CHANGELOG_CONTENT"'```
                }
              }
            ]
          }'
