name: Post CHANGELOG to Slack

on:
  push:
    branches:
      - main
jobs:
  post_changelog_to_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          node-version: '20'  # Node.js 20 강제로 설정

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Verify Node.js version
        run: node -v

      - name: Read the latest CHANGELOG entry
        id: changelog
        run: |
          # Extract the content under the most recent version header in CHANGELOG.md
          CHANGELOG=$(awk 'f{print} /^## /{if(f) exit; f=1}' CHANGELOG.md)
          echo "$CHANGELOG"
          echo "::set-output name=changelog::$CHANGELOG"

      - name: Send to Slack via Webhook
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          CHANGELOG_CONTENT: ${{ steps.changelog.outputs.changelog }}
        run: |
          curl -X POST $SLACK_WEBHOOK_URL \
          -H 'Content-type: application/json' \
          --data '{"text": "'"$CHANGELOG_CONTENT"'"}'
