name: Post CHANGELOG to Slack

on:
  push:
    branches:
      - main

jobs:
  post_changelog_to_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Verify CHANGELOG.md exists
        run: |
          if [ ! -f "CHANGELOG.md" ]; then
            echo "CHANGELOG.md not found!"
            exit 1
          else
            echo "CHANGELOG.md found."
          fi

      - name: Read the latest CHANGELOG entry
        id: changelog
        run: |
          # Debugging: Check the contents of CHANGELOG.md
          echo "Content of CHANGELOG.md:"
          cat CHANGELOG.md  # Output the entire file to the GitHub Actions log

          # Extract the section for the latest version (e.g., 0.9.0)
          CHANGELOG=$(awk '/^0\.9\.0/{flag=1;next}/^0\.[0-9]+\.[0-9]+/{flag=0}flag' CHANGELOG.md)
          
          echo "Extracted CHANGELOG content:"
          echo "$CHANGELOG"  # Debugging: Output the extracted changelog content
          
          # Check if the content is empty
          if [ -z "$CHANGELOG" ]; then
            echo "No content extracted from CHANGELOG.md for version 0.9.0"
            exit 1
          fi

          echo "::set-output name=changelog::$CHANGELOG"

      - name: Send to Slack via Webhook
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          CHANGELOG_CONTENT: ${{ steps.changelog.outputs.changelog }}
        run: |
          echo "Sending the following content to Slack:"
          echo "$CHANGELOG_CONTENT"
          
          if [ -z "$CHANGELOG_CONTENT" ]; then
            echo "No content to send to Slack."
            exit 1
          fi
          
          curl -X POST $SLACK_WEBHOOK_URL \
          -H 'Content-type: application/json' \
          --data '{"text": "'"$CHANGELOG_CONTENT"'"}'
